defaults:
  - _self_
  - arch: fully_connected
  - optimizer: adam
  - scheduler: exponential_lr
  - training: standard

# --- DIRECTORIES ---
network_dir: "."
initialization_network_dir: ""

# --- OUTPUT & LOGGING ---
save_filetypes: "vtk"
summary_histograms: false
summary_system_stats: false

# --- STOPPING CRITERIA ---
stop_criterion:
  metric: null
  min_delta: null
  patience: null
  mode: "min"
  freq: null
  strict: false

# --- PERFORMANCE ---
profiler: false
jit: true
cuda_graphs: true
amp: false
dummy_input: null
run_mode: "train"
